___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Series, Session - 3</p><h1>

## Creating a Pandas Series

In [ ]:
import numpy as np
import pandas as pd

### Creating a Pandas Series with Basic Format

In [ ]:
pd.Series([2,3,6,5])

0    2
1    3
2    6
3    5
dtype: int64

In [ ]:
ser = pd.Series([2,3,6,5])

### Creating Pandas Series by Using a ``list``, numpy array or ``dict``ionary

In [ ]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [ ]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [ ]:
pd.Series(data = arr, index = labels)

a    10
b    20
c    30
dtype: int32

### **Using Dictionary**

In [ ]:
d

{'a': 10, 'b': 20, 'c': 30}

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(data = d, index= ['q', 'c', 'y'])

q     NaN
c    30.0
y     NaN
dtype: float64

### Using Scalar Value

In [ ]:
pd.Series(data = "Steve")

0    Steve
dtype: object

In [ ]:
pd.Series(data = "Steve", index = range(3))

0    Steve
1    Steve
2    Steve
dtype: object

In [ ]:
pd.Series(data = 10, index= ['a', 'b', 'c'])

a    10
b    10
c    10
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [ ]:
set1 = (1,2,3,6)

In [ ]:
pd.Series(set1)

0    1
1    2
2    3
3    6
dtype: int64

In [ ]:
pd.Series(set)

0    <class 'set'>
dtype: object

In [ ]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [ ]:
pd.Series([sum, print, len])[1]("a")

a


In [ ]:
mix_data = ['Aziz', 2, True]

In [ ]:
pd.Series(mix_data)[1]

2

In [ ]:
type(pd.Series(mix_data)[1])

int

In [ ]:
np.array(mix_data)

array(['Aziz', '2', 'True'], dtype='<U4')

In [ ]:
type(np.array(mix_data)[1])

numpy.str_

### Basic Attributes of Series

In [ ]:
type(ser)

pandas.core.series.Series

In [ ]:
ser.dtype

dtype('int64')

In [ ]:
ser.shape

(4,)

In [ ]:
ser.size

4

In [ ]:
len(ser)

4

In [ ]:
ser.ndim

1

In [ ]:
ser

0    2
1    3
2    6
3    5
dtype: int64

In [ ]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
ser.keys()

RangeIndex(start=0, stop=4, step=1)

In [ ]:
ser.values

array([2, 3, 6, 5], dtype=int64)

In [ ]:
for i in ser.values:
    print(i)

2
3
6
5


In [ ]:
[i for i in ser.values]

[2, 3, 6, 5]

In [ ]:
ser.items()

In [ ]:
list(ser.items())

[(0, 2), (1, 3), (2, 6), (3, 5)]

In [ ]:
for index, value in ser.items():
    print(f"Index : {index}, Value : {value}")

Index : 0, Value : 2
Index : 1, Value : 3
Index : 2, Value : 6
Index : 3, Value : 5


In [ ]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])

In [ ]:
ser

c    18
b     0
a     8
e    14
f    10
d    22
g     3
i    24
h    10
j     7
dtype: int32

In [ ]:
ser.head(3)

c    18
b     0
a     8
dtype: int32

In [ ]:
ser.tail(2)

h    10
j     7
dtype: int32

In [ ]:
ser.sample(2)

j    7
g    3
dtype: int32

In [ ]:
ser.sort_index(ascending = True)

a     8
b     0
c    18
d    22
e    14
f    10
g     3
h    10
i    24
j     7
dtype: int32

In [ ]:
ser.sort_values(ascending = False)

i    24
d    22
c    18
e    14
f    10
h    10
a     8
j     7
g     3
b     0
dtype: int32

In [ ]:
ser

c    18
b     0
a     8
e    14
f    10
d    22
g     3
i    24
h    10
j     7
dtype: int32

In [ ]:
ser.isin([5, 9])

c    False
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [ ]:
[i for i in 'clarusway']

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [ ]:
pd.Series([i for i in 'clarusway'])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [ ]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                      

In [ ]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [ ]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [ ]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [ ]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [ ]:
ser1['Germany']

2

In [ ]:
ser2['Japan']

4

In [ ]:
ser1.Germany

2

Operations are then also done based off of index:

In [ ]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [ ]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])

ser3

0    a
1    b
2    c
3    d
dtype: object

In [ ]:
ser3[0]

'a'

In [ ]:
ser3[2:]

2    c
3    d
dtype: object

In [ ]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [ ]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [ ]:
panser['terry']

121

In [ ]:
panser[0]

121

In [ ]:
index1 = ['terry', 'micheal', 'jason']

In [ ]:
panser[index1]

terry      121
micheal    200
jason       99
dtype: int64

In [ ]:
panser['terry':'orion']

terry      121
micheal    200
orion      150
dtype: int64

In [ ]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes

In [ ]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [ ]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [ ]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [ ]:
panser.items()

In [ ]:
list(panser.items())

[('terry', 121), ('micheal', 200), ('orion', 150), ('jason', 99)]

In [ ]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [ ]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [ ]:
'terry' in panser

True

In [ ]:
'bob' in panser

False

In [ ]:
panser.isin([200,150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [ ]:
121 in panser.values

True

In [ ]:
55 in panser.values

False

In [ ]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [ ]:
panser['terry'] = 90

In [ ]:
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [ ]:
panser[panser < 100] = 100
panser

terry      100
micheal    200
orion      150
jason      100
dtype: int64

In [ ]:
panser[panser > 100]

micheal    200
orion      150
dtype: int64

<h1><p style="text-align: center;">Pandas DataFrames, Session - 3</p><h1>

In [ ]:
data = [1, 2, 39, 67, 90]
data

[1, 2, 39, 67, 90]

In [ ]:
pd.DataFrame(data, columns=['column1'])

column1
0        1
1        2
2       39
3       67
4       90

In [ ]:
data2 = np.arange(1,10).reshape(3,3)
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
pd.DataFrame(data2, columns=['var1', 'var2', 'var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
data3 = np.arange(1,101).reshape(25,4)
data3

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [ ]:
df3 = pd.DataFrame(data3, columns=['var1', 'var2','var3','var4'])

In [ ]:
df3.head(3)

var1  var2  var3  var4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12

In [ ]:
df3.tail(3)

var1  var2  var3  var4
22    89    90    91    92
23    93    94    95    96
24    97    98    99   100

In [ ]:
df3.sample(2)

var1  var2  var3  var4
24    97    98    99   100
8     33    34    35    36

In [ ]:
df3.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [ ]:
for i in df3.columns:
    print(i)

var1
var2
var3
var4


In [ ]:
df3.columns = ['new1', 'new2','new3', 'new4',]

In [ ]:
df3.head()

new1  new2  new3  new4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12
3    13    14    15    16
4    17    18    19    20

In [ ]:
type(df3)

pandas.core.frame.DataFrame

In [ ]:
df3.shape

(25, 4)

In [ ]:
df3.ndim

2

In [ ]:
df3.size

100

In [ ]:
len(df3)

25

In [ ]:
df_new=pd.read_csv('../data&resources/data.csv')

In [ ]:
df_new.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

      InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom  
3  12/1/2010 8:26       3.39     17850.0  United Kingdom  
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

for your info:

* 1 dim --> vector 
* 2 dim --> matrix
* 3 dim --> tensor