___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2 (Part - 2)</p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
arr[8]

8

In [7]:
type(arr[8])     # numpy.int32 : 8'in array'in bir elemanı olduğunu ifade ediyor. 

numpy.int32

In [4]:
arr[-1]

10

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:1]

array([0])

In [8]:
type(arr[:1])

numpy.ndarray

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [12]:
arr_2d= np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
arr_2d[1]

array([20, 25, 30])

In [14]:
arr_2d[1,2]

30

In [15]:
arr_2d[1][2]

30

In [16]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [17]:
arr_2d[2]

array([35, 40, 45])

In [18]:
arr_2d[2,:]

array([35, 40, 45])

In [19]:
arr_2d[:,1]

array([10, 25, 40])

In [20]:
arr_2d[1,1]

25

In [ ]:
# Let's convert 25 to 55

In [21]:
arr_2d[1,1]= 55
arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [23]:
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
v[1]

3

In [25]:
v[3]

9

In [26]:
v[7]

21

In [27]:
index_list=[1,3,7]
v[index_list]

array([ 3,  9, 21])

In [28]:
v[[1,3,7]]

array([ 3,  9, 21])

In [29]:
arr2d = np.zeros((10,10),dtype= int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
arr2d.shape

(10, 10)

In [30]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
arr2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
length_arr= arr2d.shape[0]
length_arr

10

In [34]:
for i in range(length_arr):
    arr2d[i]=i
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [36]:
arr2d[[2, 4, 6, 8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [37]:
arr2d[[6, 4, 2, 7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [38]:
k= [6, 4, 2, 7]
arr2d[k]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

<h3>any_array[[row indices], [column indices]]</h3>

In [39]:
jj= np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
jj[[1, 2],[0, 3]]

array([ 5, 12])

In [42]:
jj[[0, 2, 3],[0, 1, 3]]

array([ 1, 10, 16])

In [ ]:
arr2d[[6, 4, 2, 7]]
# matrixte Fancy indeksleme yaptık.
# tek bir köşeli parantez ile indexleme yaparsak sadece satırların indeksine ulaşıyorum

### Using ***basic index*** and ***fancy index*** together

In [43]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
jj[1, [1,3]]

array([6, 8])

In [45]:
jj[[0, 3] , 1]

array([ 2, 14])

### Using ***basic slicing*** and ***fancy index*** together

In [48]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
jj[: , [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [47]:
jj[1:3 , [1, 2]]

array([[ 6,  7],
       [10, 11]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection on a Condition

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [50]:
arr= np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [53]:
bool_arr= arr>4

In [54]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [56]:
arr[(arr!=3) & (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[:5]= 77
#show
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [60]:
a = [0, 2, 4, 6, 8, 10]

In [61]:
a[0:3]= [100]
a

[100, 6, 8, 10]

In [62]:
a[0:3]= [100, 100,100]   # listelerde ancak bu sekilde yapabiliyoruz
a

[100, 100, 100, 10]

In [68]:
arr= np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
slice_of_arr= arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [74]:
slice_of_array= 99
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr_copy= arr.copy()

In [ ]:
arr_copy[:6]=[0,1,2,3,4,5,]

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [75]:
import numpy as np
arr = np.arange(0,10)

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [79]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
import warnings
warnings.filterwarnings('ignore')

In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [83]:
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [85]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [86]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [88]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [89]:
np.max(arr)

9

In [94]:
np.amax(arr)

9

In [90]:
np.min(arr)

0

In [93]:
np.amin(arr)

0

In [91]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [92]:
np.sin(np.pi/2)

1.0

In [95]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [96]:
np.log10(1000)

3.0

In [97]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [99]:
np.subtract(v,1)

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

In [100]:
np.subtract(v,v)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
v-v

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
v**2

array([  0,   9,  36,  81, 144, 225, 324, 441, 576, 729], dtype=int32)

In [103]:
np.power(v,2)

array([  0,   9,  36,  81, 144, 225, 324, 441, 576, 729], dtype=int32)

In [104]:
np.power(v,3)

array([    0,    27,   216,   729,  1728,  3375,  5832,  9261, 13824,
       19683], dtype=int32)

In [109]:
a = np.array([[0, 1, 6],
             [2, 4, 1]])
np.max(a)
#output: 6 (bearbeitet) 

6

In [110]:
np.max(a, axis=0) # max of each column     # sütunlardaki max satir elemani 
#output : array([2, 4, 6])

array([2, 4, 6])

In [ ]:
 #axis = 0 yaparsak 0 aksisi üzerinde yani satırlar üzerinde işlem yapıyor dolayısıyla her sütundaki maksimum değeri veriyor

In [117]:
np.max(a, axis=1)              # satirlardaki max sütun elemani

array([6, 4])

## Statistical Calculations

In [105]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [107]:
np.mean(v)

2.142857142857143

In [108]:
np.median(v)

2.0

In [112]:
np.sum(v)

15

In [114]:
from scipy import stats

In [115]:
stats.mode(v)

ModeResult(mode=array([3]), count=array([3]))

In [116]:
v.max(axis=0)

3

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``arr.corrcoef()`` | Returns correlation coefficient of array

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.