___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Series, Session - 3</p><h1>

## Creating a Pandas Series

In [1]:
import numpy as np
import pandas as pd

### Creating a Pandas Series with Basic Format

In [2]:
ser= pd.Series([2, 3, 6, 5])
ser

0    2
1    3
2    6
3    5
dtype: int64

In [2]:
np.array([2,3, 6, 5])

array([2, 3, 6, 5])

### Creating Pandas Series by Using a ``list``, numpy array or ``dict``ionary

In [3]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [ ]:
pd.Series(labels)

In [ ]:
pd.Series(my_list)

### **Using NumPy Arrays**

In [ ]:
pd.Series(data=arr, index=labels)     # indexim uzerinde degisiklik yapabiliyorum 

### **Using Dictionary**

In [ ]:
d

In [ ]:
pd.Series(d)

In [4]:
pd.Series(data=d, index= ['q', 'c', 'y'])   # q ve y dictinionary icinde olmadigindan onlarin degerlerini bulamadi

q     NaN
c    30.0
y     NaN
dtype: float64

In [5]:
pd.Series(data=d, index= ['q', 'c', 'c', 'a', 'a' ,'y'])  #duplizirien

q     NaN
c    30.0
c    30.0
a    10.0
a    10.0
y     NaN
dtype: float64

### Using Scalar Value

In [6]:
pd.Series(data='Steve')

0    Steve
dtype: object

In [7]:
pd.Series(data='Steve', index= range(3))

0    Steve
1    Steve
2    Steve
dtype: object

In [8]:
pd.Series(data=10, index= ['a', 'b', 'c'])

a    10
b    10
c    10
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [9]:
set1=(1, 2,3, 6)
set1

(1, 2, 3, 6)

In [10]:
pd.Series(set1)

0    1
1    2
2    3
3    6
dtype: int64

In [11]:
pd.Series(set)

0    <class 'set'>
dtype: object

In [12]:
pd.Series(list)

0    <class 'list'>
dtype: object

In [13]:
pd.Series([set, list, len])

0              <class 'set'>
1             <class 'list'>
2    <built-in function len>
dtype: object

In [14]:
pd.Series([set, list, len])[0]

set

In [15]:
pd.Series([set, list, len])[2]

<function len(obj, /)>

In [16]:
pd.Series([set, print, len])[1]("Matthew")

Matthew


In [17]:
pd.Series([set, print, len])[2]("Matthew")

7

In [ ]:
pd.Series([set, print, len])[0]("Matthew")

In [ ]:
pd.Series([set, print("Matthew"), len])

In [ ]:
pd.Series([set, print("Matthew"), len])[1]

In [ ]:
mix_data= ['Steve', 2, True]
mix_data

In [ ]:
pd.Series(mix_data)

In [ ]:
pd.Series(mix_data)[0]

In [ ]:
pd.Series(mix_data)[1]

In [ ]:
pd.Series(mix_data)[2]

In [ ]:
np.array(mix_data)     # array bana kisitlama getiriyor hepsini string olarak verdi.

### Basic Attributes of Series

In [ ]:
ser

In [ ]:
type(ser)

In [ ]:
ser.dtype

In [ ]:
ser.shape

In [ ]:
ser.ndim

In [ ]:
ser.size

In [ ]:
ser.index    #range olarak veriyor , cook uzun taplolarimiz olabilir.  stop:exlusiv

In [ ]:
ser.keys()

In [ ]:
ser.values             # attribute old. icin parantez kullanmiyoruz

In [ ]:
for i in ser.values:
    print(i)

In [ ]:
[i for i in ser.values]         # list comprehension

In [ ]:
ser.items()

In [ ]:
print(*ser)

In [ ]:
for index, value in ser.items():
    print(f"Index: {index}, Value: {value}")

In [ ]:
list(ser.items())

In [ ]:
ser.items

In [ ]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

In [ ]:
ser.head()        # first 5 

In [ ]:
ser.tail()         # last 5

In [ ]:
ser.sample()      # rstgele default=1  tane cekiyor 

In [ ]:
ser.sample(5)

In [ ]:
ser.sort_index()     # default degeri True 

In [ ]:
ser.sort_index(ascending= False)

In [ ]:
ser.sort_values()

In [ ]:
ser.sort_values(ascending= False)

In [ ]:
ser.isin([5])    # bu bunun icinde mi

In [ ]:
ser.isin([7]) 

In [ ]:
ser.isin([7, 12]) 

In [ ]:
[i for i in 'clarusway']

In [ ]:
pd.Series([i for i in 'clarusway'])

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [ ]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [ ]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [ ]:
ser1

In [ ]:
ser2

In [ ]:
ser1.sort_index()

In [ ]:
ser1.sort_values()

In [ ]:
ser2.sort_values()

In [ ]:
ser1[0]

In [ ]:
ser1["Germany"]

In [ ]:
ser1.Germany

In [ ]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

In [ ]:
ser3[0]

In [ ]:
ser3[2:]

In [ ]:
ser3[::-1]

### pandas_series[index] | pandas_series[[indices, indices...]]

In [ ]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

In [ ]:
panser.index

In [ ]:
panser.index[0]

In [ ]:
panser["terry"]

In [ ]:
panser.terry

In [ ]:
panser[0]

In [ ]:
ind1= ["terry", "micheal", "orion"]

In [ ]:
panser[ind1]

In [ ]:
panser[["terry", "micheal", "orion"]]

In [ ]:
panser["terry":"orion"]   # labelleri  yazdigimizda sondaki labeli da veriyor ama indexleme de bu yok

In [ ]:
panser[0:2]

In [ ]:
panser[0:3]

<h1><p style="text-align: center;">Pandas DataFrames, Session - 3</p><h1>

In [ ]:
data= [1, 2, 39, 67, 90]
data

In [ ]:
pd.DataFrame(data, columns= ["column1"])

In [ ]:
pd.DataFrame(data)

In [ ]:
data2= np.arange(1,10).reshape(3,3)
data2

In [ ]:
pd.DataFrame(data2)

In [ ]:
pd.DataFrame(data2, columns= ['var1', 'var2', 'var3'])

In [ ]:
data3= np.arange(1, 101).reshape(20,5)
data3

In [ ]:
df3= pd.DataFrame(data3, columns=['var1', 'var2', 'var3', 'var4', 'var5'])
df3

In [ ]:
df3.head()

In [ ]:
df3.head(10)

In [ ]:
df3.tail()

In [ ]:
df3.tail(10)

In [ ]:
df3.sample()     #her calistirdigimizda farkli satir getirir

In [ ]:
df3.sample(5)

In [ ]:
df3.sample(22)        # 22 satirimiz olmadigi icin hata veriyor

In [ ]:
df3.columns

In [ ]:
for i in df3.columns:
    print(i)

In [ ]:
[i for i in df3.columns]

In [ ]:
df3['var3']

In [ ]:
df3[["var3"]]

In [ ]:
df3.head()

In [ ]:
df3.shape

In [ ]:
df3.ndim

In [ ]:
df3.size

In [ ]:
len(df3)

In [7]:
new_df= pd.read_csv("data.csv", encoding= 'unicode_escape')
new_df

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[541909 rows x 8 columns]

### Recap for Several Selecting Attributes

In [8]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [9]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [11]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [12]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [15]:
panser.items()

In [16]:
list(panser.items())

[('terry', 121), ('micheal', 200), ('orion', 150), ('jason', 99)]

In [18]:
dict((panser.items()))

{'terry': 121, 'micheal': 200, 'orion': 150, 'jason': 99}

In [17]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [19]:
print(*panser)

terry      121
micheal    200
orion      150
jason       99
dtype: int64


In [20]:
print(*(panser.items()))

('terry', 121) ('micheal', 200) ('orion', 150) ('jason', 99)


In [21]:
"terry" in panser

True

In [25]:
panser.isin(['terry'])

terry      False
micheal    False
orion      False
jason      False
dtype: bool

In [31]:
panser.index.isin(['terry'])

array([ True, False, False, False])

In [26]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [27]:
panser["terry"]            # labeling

121

In [29]:
panser[0]                  # index

121

In [30]:
panser["terry"] = 90
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [32]:
panser< 100

terry       True
micheal    False
orion      False
jason       True
dtype: bool

In [33]:
panser[panser< 100]

terry    90
jason    99
dtype: int64

In [34]:
panser[panser > 100]

micheal    200
orion      150
dtype: int64

for your info:

* 1 dim --> vector 
* 2 dim --> matrix
* 3 dim --> tensor