In [1]:
import numpy as np

In [3]:
n= [6,7,8]
n[0:2]

[6, 7]

In [4]:
n[-1]

8

In [5]:
a= np.array([6,7,8])

In [6]:
a[0:2]

array([6, 7])

In [7]:
a[-1]

8

In [8]:
a= np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [9]:
a[1,2]

3

In [10]:
a[0:2,2]

array([8, 3])

In [11]:
a[-1]

array([9, 3, 2])

In [12]:
a[-1,0:2]

array([9, 3])

In [13]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [14]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [15]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [16]:
a= np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
b= np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
np.vstack((a,b))   # dikeyde birlestirmek istedigimizde vertical stack

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
np.hstack((a,b))     # yatayda birlestirmek istersek horizontal stack(yigin, kume,istif)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [21]:
a= np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [23]:
result=np.hsplit(a,3)         # yatayda 3 farkli esit dizeye bölünür
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [24]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [25]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [26]:
result= np.vsplit(a,2)            # dikeyde bölme yapmak icin 
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [27]:
np.vsplit(a,4)    # iki column oldugu icin sadece ikiye bolebiliyoruz

ValueError: array split does not result in an equal division

In [28]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b= a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [31]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [33]:
arr = np.arange(1,8)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
arr[arr>4]

array([5, 6, 7])

In [35]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [36]:
arr_2d[0,2]

15

Arithmetic Operations with NumPy

In [43]:
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [38]:
a+2

array([3, 4, 5, 6])

In [39]:
a-2

array([-1,  0,  1,  2])

In [40]:
a*2

array([2, 4, 6, 8])

In [41]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [42]:
# a+=2  
# a

array([3, 4, 5, 6])

In [44]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [45]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [46]:
# Take the sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [47]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [48]:
a*b

array([1, 0, 3, 0])

In [50]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)

array([2., 3., 4., 5., 6.])

In [51]:
np.max(arr_2)

6

In [52]:
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [53]:
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])